hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

creativedata_croissant:
    resource: "@CreativeDataCroissantBundle/Controller/"
    type:     annotation
    prefix:   /
  
login_check:
    path:   /login/check-google
  
logout:
    path:   /logout
