# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     perso_croissant.my_user_choser:
         class: perso\CroissantBundle\UserChose\UserChose
         arguments: [ @doctrine.orm.entity_manager , @templating ,@mailer]  
     hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
     ib_user.oauth_user_provider:
        class: perso\CroissantBundle\Auth\OAuthProvider
        arguments: [@session, @doctrine, @service_container]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
