<?php

namespace perso\CroissantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class historyRepository extends EntityRepository {

    function findAllFromDate($date) {
	return $this->getEntityManager()->createQuery('
	SELECT h FROM persoCroissantBundle:history h
	WHERE h.dateCroissant >= :date_from')->setParameter('date_from', $date)->getResult();
    }
    function findAllToDate($date) {
	return $this->getEntityManager()->createQuery('
	SELECT h FROM persoCroissantBundle:history h
	WHERE h.dateCroissant <= :date_from')->setParameter('date_from', $date)->getResult();
    }
    function findAllPublic() {
	return $this->getEntityManager()->createQuery('
	SELECT h FROM persoCroissantBundle:history h 
	WHERE h.ok!=0 AND h.ok!=2')->getResult();
    }
    function findAllFromDateNotRefused($date) {
	return $this->getEntityManager()->createQuery('
	SELECT h FROM persoCroissantBundle:history h
	WHERE h.dateCroissant >= :date_from AND h.ok!=2')->setParameter('date_from', $date)->getResult();
    }

    function findAllFromDateAndIdUser($date, $idUser) {
	return $this->getEntityManager()->createQuery('
		    SELECT h FROM persoCroissantBundle:history h
		    WHERE h.dateCroissant >= :date_from AND h.idUser = :idUser')
			->setParameter('date_from', $date)->setParameter('idUser', $idUser)->getResult();
    }
 function deleteAll() {
	return $this->getEntityManager()->createQuery('
	DELETE FROM  persoCroissantBundle:history')->getResult();
    }
}
