<?php

namespace perso\CroissantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class historyRepository extends EntityRepository {

    function findAllFromDate($date) {
	$historyCroissant = $this->getEntityManager()->createQuery('
	SELECT h FROM persoCroissantBundle:history h
	WHERE h.dateCroissant >= :date_from')->setParameter('date_from', $date)->getResult();
    }

    function findAllFromDateAndIdUser($date, $idUser) {
	$historyUser = $this->getEntityManager()->createQuery('
		    SELECT h FROM persoCroissantBundle:history h
		    WHERE h.dateCroissant >= :date_from AND h.idUser = :idUser')
			->setParameter('date_from', $date)->setParameter('idUser', $idUser)->getResult();
    }

}
